### ISSUE TITLE
cmake-format version and reproducibility 

### ISSUE THREAD

**Issue by pramodk** [BlueBrain/hpc-coding-conventions#57] opened 2019-11-16 16:20 UTC
Similar to clang-format discussion about the version and reproducibility, we need to decide/select  version for cmake-format and document it in the readme. (currently we just as `pip install cmake-format`).

**Comment by pramodk** [comment] 2019-11-16 16:54
Re-looking into this again, I see that we are pinning cmake-format version to `0.4.5`. So it's ok to close this issue.

**Comment by tristan0x** [comment] 2019-11-18 08:02
Indeed, right now, hpc-coding-conventions enforce cmake-format version.
But version 0.6.0 of cmake format has been released and I personally find the formatting much better than 0.4.5. We should specify in this issue how we stand about that.

IMO the guidelines should recommend only one version of cmake-format, and every project should be free to use another one.

**Comment by matz-e** [comment] 2019-11-18 08:09
> Indeed, right now, hpc-coding-conventions enforce cmake-format version.
> But version 0.6.0 of cmake format has been released and I personally find the formatting much better than 0.4.5. We should specify in this issue how we stand about that.

Seems like the more recent version should be (maybe) more future-proof. Also, if projects are free to choose their reference formatting, will this also apply to C++?

**Comment by tristan0x** [comment] 2019-11-18 08:33
> if projects are free to choose their reference formatting, will this also apply to C++?

Yes. IMO this project provides BBP official guidelines that every project _should_ follow as well as the tools to enforce these guidelines as well as any variations of them.

**Comment by pramodk** [comment] 2019-11-19 20:11
> Also, if projects are free to choose their reference formatting, will this also apply to C++?

I wouldn't say `free to choose` to avoid too much divergence but as Tristan said some reasonable variation for specific project should be ok. But, I dont know how that is supported now; probably not because `.*format` file is copied from submodule?

I initially created this issue because I am finalising CMake branch of NEURON and noticed that we are using `0.4.5`. Once we got this merged, I don't see we easily re-formatting code with some different configuration for year (`s`).

**Comment by ohm314** [comment] 2020-02-05 08:31
After `cmake-format` version was changed from 0.4.5 to 0.6.0 we noticed in nmodl that the cmake formatting actually looks a bit weird. For example:

```cmake
set_property(DIRECTORY APPEND PROPERTY TEST_INCLUDE_FILES "${ctest_include_file}")
```
becomes
```cmake
    set_property(
      DIRECTORY
      APPEND
      PROPERTY TEST_INCLUDE_FILES "${ctest_include_file}")
```
or
```cmake
execute_process(COMMAND ${TEST_EXECUTOR} "${TEST_EXECUTABLE}" ${spec} --list-tests
                OUTPUT_VARIABLE output
                RESULT_VARIABLE result)
```
becomes
```cmake
execute_process(
  COMMAND ${TEST_EXECUTOR} "${TEST_EXECUTABLE}" ${spec} --list-tests
  OUTPUT_VARIABLE output
  RESULT_VARIABLE result)
```
but
```cmake
  add_command(set_tests_properties
              "${prefix}${test}${suffix}"
              PROPERTIES
              WORKING_DIRECTORY
              "${TEST_WORKING_DIR}"
              ${properties})
```
becomes
```cmake
  add_command(set_tests_properties "${prefix}${test}${suffix}" PROPERTIES WORKING_DIRECTORY
              "${TEST_WORKING_DIR}" ${properties})
```

After looking more closely at this i'm not sure whether 0.4.5 was more consistent than 0.6.0 but some of the choices in the new version are strange. Can we define exactly the rules and make sure this stays consistent. As mentioned above, especially in our open source projects it's undesirable that the formatting changes across `cmake-format` versions and this new version specifically will cause an extensive reformat of cmake files in nmodl.

My questions:
- was this upgrade to 0.6.0 really necessary? Did it bring anything that we need?
- can we add a parameter allowing a project to choose an older (0.4.5) version of cmake-format if they wish?

**Comment by tristan0x** [comment] 2020-02-05 08:59
> After `cmake-format` version was changed from 0.4.5 to 0.6.0 we noticed in nmodl that the cmake formatting actually looks a bit weird. For example:
> 
> ```cmake
> set_property(DIRECTORY APPEND PROPERTY TEST_INCLUDE_FILES "${ctest_include_file}")
> ```
> 
> becomes
> 
> ```cmake
>     set_property(
>       DIRECTORY
>       APPEND
>       PROPERTY TEST_INCLUDE_FILES "${ctest_include_file}")
> ```
> 
> or
> 
> ```cmake
> execute_process(COMMAND ${TEST_EXECUTOR} "${TEST_EXECUTABLE}" ${spec} --list-tests
>                 OUTPUT_VARIABLE output
>                 RESULT_VARIABLE result)
> ```
> 
> becomes
> 
> ```cmake
> execute_process(
>   COMMAND ${TEST_EXECUTOR} "${TEST_EXECUTABLE}" ${spec} --list-tests
>   OUTPUT_VARIABLE output
>   RESULT_VARIABLE result)
> ```
> 
> but
> 
> ```cmake
>   add_command(set_tests_properties
>               "${prefix}${test}${suffix}"
>               PROPERTIES
>               WORKING_DIRECTORY
>               "${TEST_WORKING_DIR}"
>               ${properties})
> ```
> 
> becomes
> 
> ```cmake
>   add_command(set_tests_properties "${prefix}${test}${suffix}" PROPERTIES WORKING_DIRECTORY
>               "${TEST_WORKING_DIR}" ${properties})
> ```

Here is a justification of the author in the 0.6.0 release notes about that:
```
Additionally, cmake-format will now tend to prefer a normal "horizontal" wrap for relatively long lists of positional arguments (e.g. source files in add_library) whereas it would previously prefer a vertical layout (one-entry per line). This is a consequence of an ambiguity between which positional arguments should be vertical versus which should be wrapped. Two planned features (layout tags and positional semantics) should help to provide enough control to get the layout you want in these lists.
```

`add_command` is a custom function, which it why cmake-format doesn't recognize positional arguments. cmake_format allows you to declare the signature of your functions in the configuration file. If your project provides a `.cmake-format.changes.yaml` in the CMake project source dir, then hpc-coding-conventions will merge it with the one it already provides.

Here is an example of file in zee to properly format a custom `add_mpi_test` function:
https://github.com/BlueBrain/zee/blob/master/.cmake-format.changes.yaml

> 
> (https://github.com/BlueBrain/nmodl/pull/252/files)
> 
> After looking more closely at this i'm not sure whether 0.4.5 was more consistent than 0.6.0 but some of the choices in the new version are strange. Can we define exactly the rules and make sure this stays consistent. As mentioned above, especially in our open source projects it's undesirable that the formatting changes across `cmake-format` versions and this new version specifically will cause an extensive reformat of cmake files in nmodl.
> 
> My questions:
> 
> * was this upgrade to 0.6.0 really necessary? Did it bring anything that we need?
> * can we add a parameter allowing a project to choose an older (0.4.5) version of cmake-format if they wish?

0.4.5 is considered unstable by the author. 0.6.0 is a rewrite that brings more control of the formatting via the configuration. According to the user **The changes in this release eliminate a number of inconsistencies and also adds the groundwork for future planned features** 
I would rather take some time to configure the formatting than allowing multiple versions.

**Comment by ohm314** [comment] 2020-03-19 10:40
I think we can close this issue since we have agreed to go with 0.6.0 the consesus was that cmake formatting is a bit weird and doesn't look very consistent, but `cmake-format` is producing reproducible results. So we decided to go with whatever `cmake-format` generates and not worry too much if at times the output looks surprising.

**Closed by ohm314** 2020-03-19 10:40 UTC
Labels: CMake integration, cmake-format, documentation
